### ISSUE TITLE
Objects without prototype chain are broken

### ISSUE THREAD

**Issue by martinhoefling** [chibicode/react-json-tree#20]
When objects are created via `Object.create(null)` they cannot be expanded and the object properties are not shown due to `Uncaught TypeError: obj.hasOwnProperty is not a function`.
The problematic part is in https://github.com/chibicode/react-json-tree/blob/master/src/JSONObjectNode.js#L32 where it is assumed that hasOwnProperty is always present.

**Comment by skleeschulte** [comment]
Did you test your solution? I don't think it will work, because `obj` is not defined. The `obj` in the error message probably originates from the transpiled code. A solution could look like this:

    if (Object.getPrototypeOf(data) === null || data.hasOwnProperty(key)) {

Unfortunately I cannot build the package myself, thus I cannot test changes and I don't want to make a PR.

**Comment by martinhoefling** [comment]
Yes, so I changed that line and got the expected behavior (in my case).

**Comment by martinhoefling** [comment]
I've pushed #23 and tested this. Works for me.

**Comment by chibicode** [comment]
Closed #23 thanks!
