### ISSUE TITLE
Allow any root node?

### ISSUE THREAD

**Issue by EvanSimpson** [chibicode/react-json-tree#5]
Right now the library only allows the root node to be an object or an array node, and any other value renders empty. Is this intentional, or would it be helpful to be able to display any value as the root node (surely at the very least adding capability for a `JSONIterableNode` as root)?

**Comment by EvanSimpson** [comment]
I managed to implement this with a small modification to `grab-node.js` and then using that to pick the root node in `index.js` on [this branch](https://github.com/EvanSimpson/react-json-tree/tree/allow-any-root).

Happy to open a PR if this is desirable to others.

**Comment by chibicode** [comment]
@EvanSimpson Hi Evan, thank you for pointing this out! I tracked it down to the original source code on Bitbucket: https://bitbucket.org/davevedder/react-json-viewer/commits/8b168f18ffd5bb53882793038a4994eeafe40b0f#Lsrc/jsx/jsonViewer.jsxT331 and this hasn't changed since. I don't see a downside to allow any root node - reusing `grab-node.js` seems like a reasonable thing to do. I'd be happy to pull in your changes.
